version: "4.2"

networks:  
  network_sso:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"

volumes:
  postgres_volume: {}
  pgAdmin_volume: {}

services:  
  postgres:
    container_name: postgres-container
    image: postgres
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    environment:
      POSTGRES_DB: JourneyHub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_volume:/var/lib/postgresql/data
    networks:
      network_sso:
        ipv4_address: "10.0.0.2"
  pgAdmin:
    container_name: pgAdmin-container
    depends_on:
      - postgres
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    healthcheck:
      test: "exit 0"
    ports:
      - "8081:80"
    volumes:
      - pgAdmin_volume:/var/lib/pgadmin
    networks:
      network_sso:
        ipv4_address: "10.0.0.3"  
  keycloak:
    container_name: keycloak-container
    image: quay.io/keycloak/keycloak:24.0.2        
    command: start-dev
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: JourneyHub
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin      
    ports:      
      - "8080:8080"      
    depends_on:      
      postgres:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: "10.0.0.4"  
  logging:
    container_name: logging-seq-container
    image: datalust/seq:latest       
    environment:      
      - ACCEPT_EULA=Y    
    ports:      
      - "8082:80"
    networks:
      network_sso:
        ipv4_address: "10.0.0.5"  